groups:
  - name: Docker
    commands:
      - name: publish
        command: ./docker/docker.sh publish
      - name: "bash: 3.11"
        command: ./docker/docker.sh 3.11-bash
      - name: "bash: 3.12"
        command: ./docker/docker.sh 3.12-bash
      - name: "bash: 3.11-slim"
        command: ./docker/docker.sh 3.11-slim-bash
      - name: "bash: 3.12-slim"
        command: ./docker/docker.sh 3.12-slim-bash
      - name: "pytest: 3.11"
        command: ./docker/docker.sh 3.11
      - name: "pytest: 3.12"
        command: ./docker/docker.sh 3.12
      - name: "pytest: 3.11-slim"
        command: ./docker/docker.sh 3.11-slim
      - name: "pytest: 3.12-slim"
        command: ./docker/docker.sh 3.12-slim
