---
name: Test

on:
  push:
    branches:
      - main

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  tests:
    name: Python ${{ matrix.os}} ${{ matrix.python-version }} tests
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python: [ "3.11", "3.12" ]

    steps:
      - shell: bash
        run: echo $TOKEN

      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install .[full]

      - name: pytest
        run: pytest src/nodeps/modules/project.py
#        run: pytest tests/test_pipmetapathfinder.py
#        run: pytest
