---
name: Test

on:
  push:
    branches:
      - main

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  tests:
    name: Python ${{ matrix.os}} ${{ matrix.python-version }} tests
    runs-on: ${{ matrix.os}}
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python: [ "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install .[full]
          pip uninstall -y nodeps

      - name: pytest
        run: pytest